[[bibliography]]
Bibliography
------------

This is a curated list of some NumPy related resources (articles, books
& tutorials) addressing different aspects of NumPy. Some are very
specific to NumPy/Scipy while some others offer a broader view on
numerical computing.

[[tutorials]]
Tutorials
~~~~~~~~~

* 100 Numpy exercises_, Nicolas P. Rougier, 2016.
* Numpy tutorial_, Nicolas P. Rougier, 2015.
* Python course_, Bernd Klein, 2015.
* An introduction to Numpy and Scipy_, M. Scott Shell, 2014.
* Python Numpy tutorial_, Justin Johnson, 2014.
* Quickstart tutorial_, Numpy developers, 2009.
* Numpy medkits_, Stéfan van der Walt, 2008.

[[articles]]
Articles
~~~~~~~~

* |article-2|_ +
Stéfan van der Walt, Chris Colbert & Gael Varoquaux, Computing in
Science and Engineering, 13(2), 2011.
+
In the Python world, NumPy arrays are the standard representation for
numerical data and enable efficient implementation of numerical
computations in a high-level language. As this effort shows, NumPy
performance can be improved through three techniques: vectorizing
calculations, avoiding copying data in memory, and minimizing operation
counts.
* |article-3|_ +
Romain Brette & Dan F. M. Goodman, Neural Computation, 23(6), 2010.
+
High-level languages (Matlab, Python) are popular in neuroscience
because they are flexible and accelerate development. However, for
simulating spiking neural networks, the cost of interpretation is a
bottleneck. We describe a set of algorithms to simulate large spiking
neural networks efficiently with high-level languages using vector-based
operations. These algorithms constitute the core of Brian, a spiking
neural network simulator written in the Python language. Vectorized
simulation makes it possible to combine the flexibility of high-level
languages with the computational efficiency usually associated with
compiled languages.
* |article-1|_ +
Travis E. Oliphant, Computing in Science & Engineering, 9(3), 2007.
+
By itself, Python is an excellent "steering" language for scientific
codes written in other languages. However, with additional basic tools,
Python transforms into a high-level language suited for scientific and
engineering code that's often fast enough to be immediately useful but
also flexible enough to be sped up with additional extensions.

[[books]]
Books
~~~~~

* SciPy Lecture Notes_, +
Gaël Varoquaux, Emmanuelle Gouillart, Olav Vahtras et al., 2016.
+
One document to learn numerics, science, and data with Python. Tutorials
on the scientific Python ecosystem: a quick introduction to central
tools and techniques. The different chapters each correspond to a 1 to 2
hours course with increasing level of expertise, from beginner to
expert.
* Python Data Science Handbook_ +
Jake van der Plas, O'Reilly, 2016.
+
The Python Data Science Handbook provides a reference to the breadth of
computational and statistical methods that are central to data—intensive
science, research, and discovery. People with a programming background
who want to use Python effectively for data science tasks will learn how
to face a variety of problems: for example, how can you read this data
format into your script? How can you manipulate, transform, and clean
this data? How can you use this data to gain insight, answer questions,
or to build statistical or machine learning models?
* Elegant SciPy: The Art of Scientific Python_ +
Juan Nunez-Iglesias, Stéfan van der Walt, Harriet Dashnow, O'Reilly,
2016.
+
Welcome to Scientific Python and its community! With this practical
book, you'll learn the fundamental parts of SciPy and related libraries,
and get a taste of beautiful, easy-to-read code that you can use in
practice. More and more scientists are programming, and the SciPy
library is here to help. Finding useful functions and using them
correctly, efficiently, and in easily readable code are two very
different things. You'll learn by example with some of the best code
available, selected to cover a wide range of SciPy and related
libraries—including scikit-learn, scikit-image, toolz, and pandas.
* Learning IPython for Interactive Computing and Data Visualization_ +
Cyrille Rossant, Packt Publishing, 2015.
+
This book is a beginner-friendly guide to the Python data analysis
platform. After an introduction to the Python language, IPython, and the
Jupyter Notebook, you will learn how to analyze and visualize data on
real-world examples, how to create graphical user interfaces for image
processing in the Notebook, and how to perform fast numerical
computations for scientific simulations with NumPy, Numba, Cython, and
ipyparallel. By the end of this book, you will be able to perform
in-depth analyses of all sorts of data.
* SciPy and NumPy_ +
Eli Bressert, O'Reilly Media, Inc., 2012
+
Are you new to SciPy and NumPy? Do you want to learn it quickly and
easily through examples and concise introduction? Then this is the book
for you. You’ll cut through the complexity of online documentation and
discover how easily you can get up to speed with these Python libraries.
* Python for Data Analysis_ +
Wes McKinney, O'Reilly Media, Inc., 2012.
+
Looking for complete instructions on manipulating, processing, cleaning,
and crunching structured data in Python? This hands-on book is packed
with practical cases studies that show you how to effectively solve a
broad set of data analysis problems, using several Python libraries.*
* Guide to NumPy_ +
Travis Oliphant, 2006
+
This book only briefly outlines some of the infrastructure that
surrounds the basic objects in NumPy to provide the additional
functionality contained in the older Numeric package (i.e.
LinearAlgebra, RandomArray, FFT). This infrastructure in NumPy includes
basic linear algebra routines, Fourier transform capabilities, and
random number generators. In addition, the f2py module is described in
its own documentation, and so is only briefly mentioned in the second
part of the book.
